---
title: "Blog-post2"
subtitle: "ETC5523: Communicating with Data - Assessement"
author: "Priscila Grecov"
date: "17/09/2020"
output: html_document
---

```{r setup, include = FALSE}
library(tidyverse)
library(sparkline)
library(DT)
library(stargazer)
library(knitr)
library(kableExtra)
library(broom)
library(tidycat)
library(scales)
library(dplyr)
library(ggplot2)
library(plotly)
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE
)
select <- dplyr::select
```


## Exploring COVID-19 daily data for Portugal

<br>  

### 1. Introduction 



<br> 

### 2. Data Description
  


<br> 

### 3. Data Analysis  



<br> 
  
```{r portugal-dataset1, include=FALSE}
dt2_COVID <- read.csv("owid-covid-data.csv")
PORT_df2 <- dt2_COVID %>%
  filter(location == "Portugal") 
PORT_df2_B <- PORT_df2[-(185:186),]
PORT_df2_B <- PORT_df2_B[-(1:2),]
PORT_df2_B$date2 <- as.Date(PORT_df2_B$date)
PORT_df2_B$Month <- months(PORT_df2_B$date2)
PORT_df2_B$Month = factor(PORT_df2_B$Month, levels=c('February','March','April','May','June','July','August'))
```

```{r set1-graphs-cases&deaths, fig.dim = c(40, 12), fig.align='center'}
library(patchwork)

bar_cases <- PORT_df2_B %>%
  ggplot(aes(x=date2)) +
  geom_col(aes(y=new_cases), color="darkblue") + 
  geom_line(aes(y=total_cases*.04), size = 1.5, color="purple") +
  theme(legend.position="none") +
  scale_y_continuous(sec.axis = sec_axis(~./0.04, labels = scales::label_comma(), breaks=seq(0, 75000, 12500),
                                         name = "total accumulated cases"), 
                     labels = scales::label_comma()) +
  scale_x_date(date_labels = "%d-%m", date_breaks  ="10 days", limits = as.Date(c('2020-03-03','2020-08-31'))) +
  theme(axis.text.x = element_text(angle=60, hjust=1, size = 30, color = 'darkblue'),
        axis.text.y = element_text(size = 35,  color = 'darkblue'),
        axis.title.y = element_text(size = 35, color = 'darkblue', face = "bold"),
        plot.title = element_text(size = 50, face = "bold", color = 'darkblue')) +
  ylab('daily qty of new cases') +
  xlab("") +
  labs(title='Evolution of cases')


bar_deaths <- PORT_df2_B %>%
  ggplot(aes(x=date2)) +
  geom_col(aes(y=new_deaths), color="darkred") + 
  geom_line(aes(y=total_deaths*.04), size = 1.5, color="darkorange") +
  theme(legend.position="none") +
  scale_y_continuous(sec.axis = sec_axis(~./0.04, labels = scales::label_comma(),
                                         name = "total accumulated deaths"), 
                     labels = scales::label_comma()) +
  scale_x_date(date_labels = "%d-%m", date_breaks  ="10 days", limits = as.Date(c('2020-03-03','2020-08-31'))) +
  theme(axis.text.x=element_text(angle=60, hjust=1, size = 30, color="darkred"),
        axis.text.y = element_text(size = 35, color="darkred"),
        axis.title.y = element_text(size = 35, color = 'darkred', face = "bold"),
        plot.title = element_text(size = 50, face = "bold", color = 'darkred')) +
  ylab('daily qty of new deaths') +
  xlab("") +
  labs(title='Evolution of deaths')

# bar_cases
# bar_deaths

bar_cases + bar_deaths + plot_layout(widths = 60, guides = "collect")
```
```{r set2-graphs-rates, fig.align="center", fig.dim = c(20, 7)}
library(ggridges)
library(tidyverse)
library(hrbrthemes)
library(viridis)
library(patchwork)

h1 <- ggplot(PORT_df2_B, aes(x = positive_rate, y = Month, fill = Month)) + 
  ggridges::geom_density_ridges(scale = 4) +
  # ggridges::geom_density_ridges(scale = 4, alpha=0.6, stat="binline", bins=30) +
  theme_ridges(font_size = 17) + 
  labs(tag = "(B)", title = 'Positive Rate of cases per tests executed (%)') +
  ylab("") +
  theme(legend.position = "none")

h2 <- ggplot(PORT_df2_B, aes(x = tests_per_case, y = Month, fill = Month)) + 
  ggridges::geom_density_ridges(scale = 4) +
  #ggridges::geom_density_ridges(scale = 4, alpha=0.6, stat="binline", bins=20) +
  theme_ridges(font_size = 17) + 
  labs(tag = "(A)", title = 'Tests executed per case detected') +
  ylab("") +
  theme(legend.position = "none")
# h1
# h2

PORT_df2_B$mortality_rate <- round((PORT_df2_B$new_deaths_per_million/PORT_df2_B$new_cases_per_million)*100,2)

h3 <- ggplot(PORT_df2_B, aes(x = mortality_rate, y = Month, fill = Month)) + 
  ggridges::geom_density_ridges(scale = 4) +
  # ggridges::geom_density_ridges(scale = 4, alpha=0.6, stat="binline", bins=30) +
  theme_ridges(font_size = 17) + 
  labs(tag = "(C)", title = 'Mortality rate per million of habitants (%)') +
  ylab("") +
  theme(legend.position = "none")
# h3

h2 + h1 + h3 + plot_layout(widths = 40, guides = "collect")
```



```{r portugal-dataset2-subnationl, include=FALSE}
dt_COVID_subnt <- read.csv("jrc-covid-19-regions-hxl.csv")
dt_COVID_subnt <- dt_COVID_subnt[-1,]
dt_COVID_subnt_PRT <- dt_COVID_subnt %>%
  filter(CountryName == "Portugal") 
dt_COVID_subnt_PRT$Date2 <- as.Date(dt_COVID_subnt_PRT$Date)
dt_COVID_subnt_PRT$CumulativePositive <- as.numeric(dt_COVID_subnt_PRT$CumulativePositive)
dt_COVID_subnt_PRT$CumulativeDeceased <- as.numeric(dt_COVID_subnt_PRT$CumulativeDeceased)
dt_COVID_subnt_PRT$CumulativeRecovered <- as.numeric(dt_COVID_subnt_PRT$CumulativeRecovered)
dt_COVID_subnt_PRT$CurrentlyPositive <- as.numeric(dt_COVID_subnt_PRT$CurrentlyPositive)
dt_COVID_subnt_PRT$Hospitalized <- as.numeric(dt_COVID_subnt_PRT$Hospitalized)
dt_COVID_subnt_PRT$IntensiveCare <- as.numeric(dt_COVID_subnt_PRT$IntensiveCare)
unique(dt_COVID_subnt_PRT$Region)
unique(dt_COVID_subnt_PRT$NUTS)
```

```{r adjusting-dataset2, include=FALSE}
dt_COVID_subnt_PRT_ready <- dt_COVID_subnt_PRT %>%
    group_by(Date2, Region, lat, lon) %>%
    summarize(Tot_Positive = sum(CumulativePositive),
              Tot_Deaths = sum(CumulativeDeceased),
              Tot_Recover = sum(CumulativeRecovered),
              Curr_Positive = sum(CurrentlyPositive),
              Hosp = sum(Hospitalized),
              IntCare = sum(IntensiveCare),
              .groups = 'drop')

dt_COVID_subnt_PRT_ready %>%
  select(Date2, Region, Tot_Positive) 

```

```{r set3-graphs-linesPerRegion, fig.dim = c(10, 4)}

graphLine_Region_cases <- dt_COVID_subnt_PRT_ready %>%
  select(Date2, Region, Tot_Positive) %>%
  filter(Region %in% c("Açores", "Alentejo", "Algarve", "Centro", "Lisbon", "Madeira", "Norte")) %>%
  ggplot(aes(x = Date2, y = Tot_Positive)) +
  geom_line(aes(color = Region), size=1.4) +
  scale_color_ipsum() +
  xlab("") +
  ylab("total number of cases") +
  scale_x_date(date_labels = "%d-%m", date_breaks  ="10 days", limits = as.Date(c('2020-03-03','2020-09-15'))) +
  scale_y_continuous(labels = scales::label_comma(), breaks = seq(0, 40000, by=5000)) +
  #theme_ipsum() +
  theme_bw(base_size = 11) +
  theme(axis.text.x=element_text(angle=60, hjust=1, size = 10),
        plot.title = element_text(size = 15, face = "bold", color = 'darkblue')) +
  labs(title = "Total cases per Region", size = 15) 

ggplotly(graphLine_Region_cases) %>%
  config(displayModeBar = F)

graphLine_Region_deaths <- dt_COVID_subnt_PRT_ready %>%
  select(Date2, Region, Tot_Deaths) %>%
  filter(Region %in% c("Açores", "Alentejo", "Algarve", "Centro", "Lisbon", "Madeira", "Norte")) %>%
  filter(Date2 > "2020-03-20") %>%
  ggplot(aes(x = Date2, y = Tot_Deaths)) +
  geom_line(aes(color = Region), size=1.4) +
  scale_color_ipsum() +
  xlab("") +
  ylab("total number of deaths") +
  scale_x_date(date_labels = "%d-%m", date_breaks  ="10 days", limits = as.Date(c('2020-03-21','2020-09-15'))) +
  scale_y_continuous(labels = scales::label_comma(),  breaks = seq(0, 900, by=150)) +
  #theme_ipsum() +
  theme_bw(base_size = 11) +
  theme(axis.text.x=element_text(angle=60, hjust=1, size = 10),
        plot.title = element_text(size = 15, face = "bold", color = 'darkblue')) +
  labs(title = "Total deaths per Region") 

ggplotly(graphLine_Region_deaths) %>%
  config(displayModeBar = F)

```


```{r data-for-choropleth, include=FALSE}
library(maptools)
library(rgdal)
library(raster)
library(rgeos)
library(ggalt)
library(ggthemes)
library(viridis)
library(magrittr)
library(gpclib)

# as stated in the other answer, this is the same as your shapefile
port_adm <- raster::getData('GADM', country='PRT', level=1)

# make the polygons a bit less verbose
gSimplify(port_adm, 
          0.01, 
          topologyPreserve=TRUE) %>%
  SpatialPolygonsDataFrame(dat=port_adm@data) -> port_adm

if (!require(gpclib)) install.packages("gpclib", type="source")
gpclibPermit()

# turn them into a data frame
port_map <- fortify(port_adm, region="NAME_1")
port_map2 <-port_map %>%
  filter(id %in% c("Aveiro", "Beja", "Braga", "Bragança", "Castelo Branco", 
                          "Coimbra", "Évora", "Faro", "Guarda", "Leiria", "Lisboa",
                          "Portalegre", "Porto", "Santarém", "Setúbal", "Viana do Castelo",
                          "Vila Real", "Viseu"))

# reproducibly simulate some data
set.seed(1492)

puntos <- data.frame(id=c("Aveiro", "Azores", "Beja", "Braga", "Bragança", "Castelo Branco", 
                          "Coimbra", "Évora", "Faro", "Guarda", "Leiria", "Lisboa",
                          "Madeira", "Portalegre", "Porto", "Santarém", "Setúbal", "Viana do Castelo",
                          "Vila Real", "Viseu"),
                     value = sample(100,20))

cases_vector <- c(23984, 1231, 23984, 23984, 5480,
                  5480, 1231, 1304, 5480, 5480, 33960,
                  1231, 23984, 5480, 1231, 23984,
                  23984, 5480)

puntos2 <- data.frame(id=c("Aveiro", "Beja", "Braga", "Bragança", "Castelo Branco", 
                          "Coimbra", "Évora", "Faro", "Guarda", "Leiria", "Lisboa",
                          "Portalegre", "Porto", "Santarém", "Setúbal", "Viana do Castelo",
                          "Vila Real", "Viseu"),
                     value = cases_vector)

```

```{r choropleth-map}
# plot it
gg <- ggplot() 

# necessary in the new world of ggplot2 mapping O_o
gg <- gg + geom_blank(data=port_map2, 
                      aes(long, lat))

# draw the base polygon layer
gg <- gg + geom_map(data=port_map2, 
                    map=port_map2, 
                    aes(map_id = id),
                    color="#b2b2b2", 
                    size=0.15, 
                    fill=NA)

# fill in the polygons
gg <- gg + geom_map(data=puntos2, 
                    map=port_map2,
                    aes(fill=value, 
                        map_id=id),
                    color="#b2b2b2", 
                    size=0.15)

gg <- gg + scale_fill_viridis(name="Total cases")
gg <- gg + theme_map()
gg <- gg + theme(legend.position=c(0.8, 0.1)) + labs(title = "Distribution of total cases by Region") 
gg
```

